### ISSUE TITLE
Book is retired?

### ISSUE THREAD

**Issue by somazx** [shageman/cbra.info#9]
LeanPub says the book has been _"retired"_. Is this because you feel cobra is no longer a worth while approach? Or just not having time to keep the book up to date with changes in rails? Or because you're opting to sell elsewhere?

**Comment by somazx** [comment]
Oh, I missed this line:
> Updated book available from Pearson

**Comment by shageman** [comment]
It's been a long time coming.. I just updated cbra.info with the new and correct info...

I will look into giving the entire site a revamp...

Thanks!
